name: Tests pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install

      - name: Run Jest
        run: yarn test
  Cypress:
    cypress-run:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          build: yarn run build
          start: yarn serve
          wait-on: "http://localhost:9000"
          headless: true
